function disp(ThisFoilGeometry)
% disp overloads the builtin disp function for FoilGeometry class

% define properties to be displayed explicitly (so that order is known and
% nothing will be missing)
propertiesList = { ...
    'perimeter'; ...
    'area'; ...
    'centroidPerimeter'; ...
    'centroidArea' ...
    };
                
detailsList = { ...
    '         Perimeter: %g '; ...
    '              Area: %g '; ...
    'Perimeter centroid: (%g, %g) '; ...
    '     Area centroid: (%g, %g) ' ...
    };
                
unitsList = { ...
    '[L]'; ...
    '[L^2]'; ...
    '[L]'; ...
    '[L]' ...
    };
% rJustTxt = strjust(propertiesList{:,1});

fprintf(['\tFoilGeometry object ''%s'' with %i coordinates in ''%s'' '...
         'format, and properties:\n\n'], ThisFoilGeometry.name,...
         numel(ThisFoilGeometry.abcissas), ThisFoilGeometry.coordinatesFormat)
     
for thisLine = 1:numel(propertiesList)
    str = ['\t', detailsList{thisLine}, unitsList{thisLine}, '\n'];
    fprintf(str, ThisFoilGeometry.(propertiesList{thisLine}))
end

fprintf('\n')

%{
fprintf(['FoilGeometry object ''%s'' with %i coordinates in ''%s'' '...
         'format, and properties:\n'], ThisFoilGeometry.name,...
         numel(ThisFoilGeometry.abcissas), ThisFoilGeometry.coordinatesFormat)
fprintf('Perimeter          [L]     =   %g\n', ThisFoilGeometry.perimeter)
fprintf('Area               [L^2]   =   %g\n', ThisFoilGeometry.area)
fprintf('Perimeter centroid [L]     =   (%g, %g)\n', ThisFoilGeometry.centroidPerimeter)
fprintf('Area centroid      [L]     =   (%g, %g)\n', ThisFoilGeometry.centroidArea)
% fprintf('Max thickness %g at %g&& of chord, measured perpendicular to it\n', ThisFoilGeometry.sweepAngle_deg)
%}
end

