function disp(ThisFinGeometry)
% disp overloads the builtin disp function for FinGeometry class

% define properties to be displayed explicitly (so that order is known and
% nothing will be missing)
propertiesList = { ...
    'referenceArea'; ...
    'aspectRatio'; ...
    'taperRatio'; ...
    'fullspan'; ...
    'rootChord'; ...
    'meanAerodynamicChord'; ...
    'macLocation'; ...
    'sweepAngle_deg'; ...
    'sweepLocation' ...
    };

fullnameList = { ...
    '                     Reference area S'; ...
    '                      Aspect ratio AR'; ...
    '                       Taper ratio TR'; ...
    '                          Full span b'; ...
    '                     Root chord cRoot'; ...
    '           Mean aerodynamic chord MAC'; ...
    '                 Location of MAC yBar'; ...
    '                   Sweep angle lambda'; ...
    'Location of constant sweep xBarLambda' ...
    };

unitsList = { ...
    '[L^2]'; ...
    '[-]'; ...
    '[-]'; ...
    '[L]'; ...
    '[L]'; ...
    '[L]'; ...
    '[L] from root'; ...
    'deg'; ...
    '\b%% of chord' ...
    };

fprintf('\tFinGeometry object with properties:\n\n')
for iRow = 1:numel(propertiesList)
    str = ['\t', fullnameList{iRow}, ': %g ', unitsList{iRow}, '\n'];
    fprintf(str, ThisFinGeometry.(propertiesList{iRow}))
end
fprintf('\n')
%{
fprintf('\tFinGeometry object with properties:\n\n')
fprintf('\t           Reference area: %g [L^2]\n', ThisFinGeometry.referenceArea)
fprintf('\t             Aspect ratio: %g [-]\n', ThisFinGeometry.aspectRatio)
fprintf('\t              Taper ratio: %g [-]\n', ThisFinGeometry.taperRatio)
fprintf('\t                Full span: %g [L]\n', ThisFinGeometry.fullspan)
fprintf('\t               Root chord: %g [L]\n', ThisFinGeometry.rootChord)
fprintf('\t              Sweep angle: %g deg\n', ThisFinGeometry.sweepAngle_deg)
fprintf('\t\bLocation of constant sweep: %g%% of chord\n\n', ThisFinGeometry.sweepLocation * 100)
%}
end
